db:
    user: summa
    password: summa-project
    port: 5432
    host: ui_stack_db
    dbname: summa
    app_name: summa-ui-stack-summarization
    pool_max_connections: 5
    reconnect_sleep: 10
summarization_api: http://localhost:5000/summarize
